export const POST_CHAR_LIMIT_DEFAULT = 480;
export const POST_CHAR_LIMIT_VERIFIED = 2000;

export const COMMENT_CHAR_LIMIT_DEFAULT = 280;
export const COMMENT_CHAR_LIMIT_VERIFIED = 1000;

export const TRUNCATED_TEXT_LINE_CLAMP = 5;
